export const MOBILE_CONTROL_BAR_HEIGHT_PX = 56;
export const MOBILE_CHAT_HANDLE_HEIGHT_PX = 48;
export const MOBILE_CHAT_MAIN_PADDING_EXTRA_PX = 84;
export const MOBILE_CHAT_SWIPE_THRESHOLD_PX = 36;
export const MOBILE_CHAT_SHEET_MAX_HEIGHT_VH = 72;
export const MOBILE_CHAT_SHEET_TRANSITION_MS = 220;
